-- MySQL Script generated by MySQL Workbench
-- Thu 20 Oct 2022 13:34:59 EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema decorations-db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `decorations-db` ;

-- -----------------------------------------------------
-- Schema decorations-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `decorations-db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `decorations-db` ;

-- -----------------------------------------------------
-- Table `decorations-db`.`electric-decoration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decorations-db`.`electric-decoration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(1500) NOT NULL,
  `amountAvalaible` INT NOT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `length` INT NOT NULL,
  `power` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `colors` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `decorations-db`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decorations-db`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `decorations-db`.`image-decoration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decorations-db`.`image-decoration` (
  `imageId` INT NOT NULL,
  `decorationId` INT NOT NULL,
  `numInList` INT NOT NULL,
  PRIMARY KEY (`decorationId`, `imageId`),
  INDEX `fk_image-decoration_1_idx` (`decorationId` ASC) VISIBLE,
  CONSTRAINT `fk_image-decoration_1`
    FOREIGN KEY (`decorationId`)
    REFERENCES `decorations-db`.`electric-decoration` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
